export interface Standard {
  id: string;
  standard: string;
  title: string;
  description: string;
  category: 'CMS' | 'JC' | 'OSHA' | 'ADHS';
  surveyorTips: string;
  keywords: string;
}

export const standardsLibrary: Standard[] = [
  // ── CMS Conditions of Participation ─────────────────────────────
  {
    id: 'cms-482.13a',
    standard: '42 CFR 482.13(a)',
    title: 'Patient Rights: Notice of Rights',
    description: 'Hospitals must inform each patient of their rights in advance of furnishing or discontinuing patient care. Must be provided in writing in a language and manner the patient understands.',
    category: 'CMS',
    surveyorTips: 'Surveyors will request your patient rights notice, verify it is available in the languages spoken by your patient population, and check that staff can explain the process for notifying patients. Review your admission packet and check for documentation that rights were communicated.',
    keywords: 'patient rights notice admission language interpreter',
  },
  {
    id: 'cms-482.13b',
    standard: '42 CFR 482.13(b)',
    title: 'Patient Rights: Exercise of Rights',
    description: 'The patient or their representative has the right to participate in the development and implementation of the plan of care. Patients have the right to make decisions regarding their medical care, including the right to accept or refuse treatment.',
    category: 'CMS',
    surveyorTips: 'Review a sample of medical records for documented patient participation in care planning. Surveyors may interview patients about whether they feel involved in their care decisions. Check advance directive documentation - a common deficiency is failure to document patient preferences regarding advance directives.',
    keywords: 'care planning advance directive informed consent refuse treatment',
  },
  {
    id: 'cms-482.13e',
    standard: '42 CFR 482.13(e)',
    title: 'Patient Rights: Grievance Process',
    description: 'Hospitals must have a process for prompt resolution of patient grievances and must inform each patient who has a grievance of the hospital\'s grievance process. Written notice of grievance determination must be provided. Acknowledgment within 7 days; resolution within 30 days (or notify of delay).',
    category: 'CMS',
    surveyorTips: 'Surveyors will test the entire grievance system: log completeness, written acknowledgment letters, resolution letters with specific language required by regulation, and timelines. Review your grievance log for any unresolved items over 30 days. Grievance letters must include the name of the hospital contact, the steps taken, the results, and the date of completion.',
    keywords: 'grievance complaint resolution 7-day 30-day written notice',
  },
  {
    id: 'cms-482.13f',
    standard: '42 CFR 482.13(f)',
    title: 'Patient Rights: Restraint and Seclusion',
    description: 'Patients have the right to be free from restraints and seclusion unless clinically necessary. Restraint orders must be time-limited, renewed every 24 hours by a physician. Continuous monitoring required. Deaths involving restraint or seclusion must be reported to CMS.',
    category: 'CMS',
    surveyorTips: 'This is one of the most frequently cited CoPs. Surveyors observe restrained patients directly. Check that RN assessment and monitoring documentation is complete, physician orders are current and time-limited, and that all staff have completed required restraint training. Verify your CMS reporting log for restraint-related deaths.',
    keywords: 'restraint seclusion monitoring physician order death reporting',
  },
  {
    id: 'cms-482.21',
    standard: '42 CFR 482.21',
    title: 'Quality Assessment and Performance Improvement (QAPI)',
    description: 'Hospitals must maintain a QAPI program that is hospital-wide and data-driven. The program must measure, analyze, and track quality indicators and adverse patient events. Hospitals must implement preventive actions and demonstrate measurable improvement.',
    category: 'CMS',
    surveyorTips: 'Surveyors expect to see a written QAPI plan, a data-driven priority list, documented improvement projects with measurable outcomes, and leadership involvement. Be prepared to walk surveyors through at least 2-3 active quality improvement projects with data showing progress. Dashboards and run charts are effective evidence.',
    keywords: 'QAPI quality improvement data-driven adverse events performance',
  },
  {
    id: 'cms-482.22',
    standard: '42 CFR 482.22',
    title: 'Medical Staff',
    description: 'Hospitals must have an organized medical staff responsible for quality of care provided to patients. Medical staff must operate under bylaws approved by the governing body and must be accountable to the governing body.',
    category: 'CMS',
    surveyorTips: 'Review medical staff bylaws for currency and governing body approval. Surveyors will check credentialing files - verify that all privileged practitioners have current credentials, competency documentation, and peer review. Expired credentials are a common deficiency.',
    keywords: 'medical staff bylaws credentialing privileges peer review governing body',
  },
  {
    id: 'cms-482.23',
    standard: '42 CFR 482.23',
    title: 'Nursing Services',
    description: 'Hospitals must have an organized nursing service that provides 24-hour nursing care. There must be a sufficient number of qualified RNs to assess patient needs and ensure nursing care is planned and delivered by qualified staff.',
    category: 'CMS',
    surveyorTips: 'Staffing ratios and competency documentation are focal points. Surveyors will review staff schedules, competency files, and may observe nursing practice directly. Ensure float pool and agency nurses have facility-specific orientation documented. Licensed nursing staff must have a valid, unencumbered license - verify with the state board before each shift.',
    keywords: 'nursing staffing ratios RN competency 24-hour care',
  },
  {
    id: 'cms-482.24',
    standard: '42 CFR 482.24',
    title: 'Medical Record Services',
    description: 'Hospitals must maintain a medical record for each inpatient and outpatient. Medical records must be retained and contain sufficient information to justify diagnosis and treatment. Records must be completed within 30 days of discharge.',
    category: 'CMS',
    surveyorTips: 'Record completeness and timeliness are common deficiencies. Surveyors will pull records and check for all required elements: authentication, operative reports, discharge summaries, and informed consent. Run a delinquent record report before survey - any record over 30 days delinquent is a finding.',
    keywords: 'medical records documentation delinquent discharge summary informed consent',
  },
  {
    id: 'cms-482.25',
    standard: '42 CFR 482.25',
    title: 'Pharmaceutical Services',
    description: 'Hospitals must have pharmaceutical services meeting the needs of patients. A pharmacist licensed to practice in the state must be responsible for pharmaceutical services. Medications must be controlled and distributed in a safe manner.',
    category: 'CMS',
    surveyorTips: 'High-alert medications and look-alike/sound-alike drugs are priority review areas. Check controlled substance logs for accuracy. Surveyors will inspect medication storage areas, refrigerator temperatures, and check for expired medications. The formulary and medication error tracking process are commonly reviewed.',
    keywords: 'pharmacy medications controlled substances high-alert expired formulary',
  },
  {
    id: 'cms-482.27',
    standard: '42 CFR 482.27',
    title: 'Laboratory Services',
    description: 'Hospitals must maintain or have access to laboratory services to meet the needs of patients. Laboratory services must be available 24 hours a day. The laboratory must be certified under CLIA.',
    category: 'CMS',
    surveyorTips: 'Verify CLIA certificate currency and ensure it covers all tests performed. Critical value notification and documentation process is frequently reviewed - check logs for timely physician notification of critical values. Point-of-care testing must be included in QC programs.',
    keywords: 'laboratory CLIA critical values point-of-care testing quality control',
  },
  {
    id: 'cms-482.41',
    standard: '42 CFR 482.41',
    title: 'Physical Environment',
    description: 'Hospitals must maintain a safe, functional, and sanitary physical environment. The hospital must comply with Life Safety Code requirements. Fire safety, emergency power, and environment of care must meet applicable standards.',
    category: 'CMS',
    surveyorTips: 'Environment rounds are a major part of any survey. Walk every clinical area looking for: unsecured sharps, blocked fire exits, unlocked hazardous materials, expired emergency equipment, and failed Life Safety Code requirements. Surveyors will pull fire drill logs, fire suppression test records, and generator test logs.',
    keywords: 'environment life safety fire exits emergency power cleanliness',
  },
  {
    id: 'cms-482.42',
    standard: '42 CFR 482.42',
    title: 'Infection Control',
    description: 'Hospitals must have an active program for the prevention, control, and investigation of infections and communicable diseases. A qualified infection control officer must be designated. The program must include surveillance, analysis, and corrective actions.',
    category: 'CMS',
    surveyorTips: 'Infection control is a top-cited CoP. Hand hygiene compliance rates, HAI surveillance data, and PPE availability are focal points. Surveyors observe clinical care and PPE use in real time. Have your CAUTI, CLABSI, SSI, and C. diff data organized and ready to discuss with root cause analyses for any outliers.',
    keywords: 'infection control hand hygiene HAI CAUTI CLABSI PPE surveillance',
  },
  {
    id: 'cms-482.43',
    standard: '42 CFR 482.43',
    title: 'Discharge Planning',
    description: 'Hospitals must have a discharge planning process that applies to all patients. The process must identify patients with anticipated post-discharge needs and must include a discharge planning evaluation. Patients must be informed of their right to a discharge planning evaluation.',
    category: 'CMS',
    surveyorTips: 'Review a sample of records for discharge planning documentation initiated within 24 hours. Surveyors check that patients were offered choices among discharge options, including home health agencies. Post-acute transfer documentation and PASRR screens for nursing facility placements are commonly reviewed.',
    keywords: 'discharge planning post-acute home health patient choice PASRR',
  },
  {
    id: 'cms-482.45',
    standard: '42 CFR 482.45',
    title: 'Organ, Tissue, and Eye Procurement',
    description: 'Hospitals must have and implement written protocols for identifying potential donors and for notifying the OPO (Organ Procurement Organization). All deaths and imminent deaths must be reported to the OPO.',
    category: 'CMS',
    surveyorTips: 'Verify a current agreement with your designated OPO. Review death records to confirm all deaths were reported to the OPO within the required timeframe. Surveyors will check that staff know the OPO contact process and that documentation of OPO notification is present in medical records.',
    keywords: 'organ tissue donation OPO death reporting donor protocols',
  },
  // ── Joint Commission Standards ────────────────────────────────────
  {
    id: 'jc-npsg1',
    standard: 'NPSG.01.01.01',
    title: 'Improve the Accuracy of Patient Identification',
    description: 'Use at least two patient identifiers when providing care, treatment, or services. Acceptable identifiers include patient name, assigned identification number, date of birth, or phone number.',
    category: 'JC',
    surveyorTips: 'Tracer activity will include direct observation of staff using two identifiers before medication administration, blood draws, and procedures. Staff must be able to verbalize the two-identifier policy. Surveyors frequently find identifiers posted on doors or rooms instead of verifying directly with the patient - that does not count.',
    keywords: 'patient identification two identifiers name DOB armband',
  },
  {
    id: 'jc-npsg2',
    standard: 'NPSG.02.03.01',
    title: 'Improve Communication Among Caregivers',
    description: 'Report critical values of tests and diagnostic procedures in a timely manner. Establish and implement a process for communicating critical test results to the responsible licensed caregiver in a timely manner.',
    category: 'JC',
    surveyorTips: 'Surveyors will pull medical records to verify critical value documentation includes: value, who was called, who received the call, time of call, and time of read-back. Gaps in any of these fields are findings. Review your critical value log monthly before survey.',
    keywords: 'critical values communication SBAR read-back timely notification',
  },
  {
    id: 'jc-npsg3',
    standard: 'NPSG.03.04.01',
    title: 'Label All Medications and Containers',
    description: 'Label all medications and other solutions on and off the sterile field in perioperative and other procedural settings. Labels must include drug name, strength, amount, and expiration when not used within 24 hours.',
    category: 'JC',
    surveyorTips: 'Surveyors observe in real time during procedures. Any unlabeled syringe on a sterile field is an immediate finding. Conduct observation tracers in OR, procedural areas, and IV preparation areas. Staff must demonstrate the labeling process and know what information is required.',
    keywords: 'medication labeling syringes sterile field OR perioperative unlabeled',
  },
  {
    id: 'jc-npsg6',
    standard: 'NPSG.06.01.01',
    title: 'Alarm Safety: Clinical Alarm Management',
    description: 'Improve the safety of clinical alarm systems. Hospitals must develop policies for managing alarms, establish alarm settings for individual units, and monitor staff response to alarms.',
    category: 'JC',
    surveyorTips: 'Alarm fatigue is a top safety concern. Surveyors observe alarm response times and may review event data for alarm silencing patterns. Check that your default alarm parameters are set appropriately by unit, staff know the escalation process for unanswered alarms, and your alarm committee is meeting regularly with data.',
    keywords: 'alarms alarm fatigue monitoring response time cardiac telemetry',
  },
  {
    id: 'jc-npsg7',
    standard: 'NPSG.07.01.01',
    title: 'Hand Hygiene',
    description: 'Comply with current hand hygiene guidelines from CDC or WHO. Set goals for improving hand hygiene compliance and improve compliance with hand hygiene guidelines.',
    category: 'JC',
    surveyorTips: 'Hand hygiene is observed in real time throughout the survey. Surveyors watch before and after patient contact. Dispenser availability, product availability, and staff technique are all observed. Have current compliance rates available - surveyors will ask. Rates below 90% invite increased scrutiny.',
    keywords: 'hand hygiene hand washing CDC WHO compliance rate dispenser',
  },
  {
    id: 'jc-npsg15',
    standard: 'NPSG.15.01.01',
    title: 'Suicide Risk Reduction',
    description: 'Use a validated risk assessment to identify patients at risk for suicide. Implement environmental controls to prevent suicide attempts in behavioral health settings.',
    category: 'JC',
    surveyorTips: 'Surveyors review how patients flagged as suicidal are managed: ligature risk assessment of patient rooms, removal of potentially dangerous items, documentation of 1:1 observation initiation. Any gap between a positive screen and safety interventions is a finding. Show your environmental risk assessment for your behavioral health unit.',
    keywords: 'suicide risk behavioral health ligature observation safety assessment',
  },
  {
    id: 'jc-rc1',
    standard: 'RC.01.01.01',
    title: 'Medical Record Initiation and Content',
    description: 'A medical record is initiated for every patient. Records contain sufficient information to identify the patient, support the diagnosis, justify the treatment, document results, and promote continuity of care among providers.',
    category: 'JC',
    surveyorTips: 'Surveyors pull records from a random sample and trace every required element. Missing authentication, unsigned orders, and missing H&P within 24 hours are common findings. Run a record audit before survey using the RC standards checklist.',
    keywords: 'medical record documentation H&P history physical authentication orders',
  },
  {
    id: 'jc-rc2',
    standard: 'RC.02.01.01',
    title: 'Medical Record Content Requirements',
    description: 'The medical record contains the information required by law and regulation. Required elements include: reason for admission, findings, procedures, diagnoses, patient condition at discharge, and discharge instructions.',
    category: 'JC',
    surveyorTips: 'Discharge instructions that are absent, incomplete, or not in a language the patient understands are a consistent finding. Surveyors verify that instructions address follow-up appointments, medication changes, activity restrictions, and warning signs. Have a discharge instruction template that covers all required elements.',
    keywords: 'discharge instructions diagnoses procedures reason for admission discharge summary',
  },
  {
    id: 'jc-ec1',
    standard: 'EC.02.01.01',
    title: 'Safety and Security Management Plan',
    description: 'The hospital manages safety and security risks. Must identify security-sensitive areas, establish a process to identify patients, visitors, and staff, and maintain records of security incidents.',
    category: 'JC',
    surveyorTips: 'Infant/child abduction prevention is a focus - surveyors will trace your HUGS/security band system. Review your security incident log. Surveyors will check that your security management plan is current, staff know reporting processes, and that workplace violence incidents are tracked in your QAPI program.',
    keywords: 'security infant abduction workplace violence safety management plan',
  },
  {
    id: 'jc-ec2',
    standard: 'EC.02.03.05',
    title: 'Fire Safety: Fire Drills',
    description: 'Fire drills must be conducted at least quarterly for each shift on each floor or unit. Drills are evaluated for staff response and corrective action is implemented for identified deficiencies.',
    category: 'JC',
    surveyorTips: 'Maintain fire drill logs with dates, times, floors, shifts, participants, and critique notes. Surveyors count drills by shift - many hospitals miss the night shift quarterly requirement. Ensure drill critique documentation shows that identified gaps were addressed in subsequent drills.',
    keywords: 'fire drill quarterly shifts log critique corrective action',
  },
  {
    id: 'jc-ec3',
    standard: 'EC.02.05.07',
    title: 'Utility Systems: Emergency Generators',
    description: 'Emergency generators must be tested at least monthly for 30 minutes. Load bank testing or an equivalent test must be performed annually. Testing documentation must be maintained.',
    category: 'JC',
    surveyorTips: 'Generator test logs are always reviewed. Ensure the monthly 30-minute run log is complete and that transfer time to generator power is documented. If a generator failed to start or transfer, document the corrective action taken. Verify that the annual load bank or equivalent test is current.',
    keywords: 'emergency generator testing monthly annual load bank transfer switch',
  },
  {
    id: 'jc-hr1',
    standard: 'HR.01.04.01',
    title: 'Staff Orientation, Training, and Education',
    description: 'Staff receive orientation to the hospital and to their assigned responsibilities. Ongoing education and training are provided. Competency assessments are completed upon hire and at least annually.',
    category: 'JC',
    surveyorTips: 'Surveyors randomly select staff and request to see their competency and education files. Files must show: initial orientation completion, annual competency assessments specific to their role, and completion of all required trainings (restraint, abuse, fire safety, etc.). Gaps in any required training are findings.',
    keywords: 'orientation competency training education annual staff',
  },
  {
    id: 'jc-hr2',
    standard: 'HR.01.06.01',
    title: 'Staff Competence Assessment',
    description: 'The hospital defines the competencies required for each position. Staff competency is assessed when hired and when new or changed responsibilities are introduced. Results of competency assessment are used to determine educational needs.',
    category: 'JC',
    surveyorTips: 'Competency assessments must be role-specific and must include methods beyond a written test for skills-based competencies (e.g., return demonstration, simulation, direct observation). Surveyors look for evidence that failed competencies triggered remediation and re-assessment.',
    keywords: 'competency assessment role-specific skills demonstration remediation',
  },
  {
    id: 'jc-ld1',
    standard: 'LD.04.04.05',
    title: 'Safety Culture and Environment',
    description: 'Leaders create and maintain a culture of safety and quality throughout the hospital. Processes must be in place for identifying and managing behaviors that undermine a safety culture.',
    category: 'JC',
    surveyorTips: 'Surveyors conduct confidential staff interviews throughout the survey asking about safety culture, willingness to report errors, and concerns about intimidating behaviors. Your Culture of Safety survey data should be available. Show the actions taken in response to survey findings - data alone without action is a deficiency.',
    keywords: 'safety culture leadership staff interviews intimidating behavior reporting',
  },
  {
    id: 'jc-pi1',
    standard: 'PI.01.01.01',
    title: 'Data Collection for Performance Improvement',
    description: 'Hospitals collect data to monitor the performance of processes, outcomes, and patient safety goals. Data collection must be systematic and ongoing. Priority must be given to high-risk, high-volume, and problem-prone processes.',
    category: 'JC',
    surveyorTips: 'Surveyors ask to see what data you collect, how it is analyzed, and what you do with the results. Every department should have at least one monitored indicator. Make sure your data collection covers all NPSGs and includes infection control, medication safety, and transfusion reactions at minimum.',
    keywords: 'data collection performance improvement indicators high-risk monitoring',
  },
  {
    id: 'jc-mm1',
    standard: 'MM.01.01.03',
    title: 'High-Alert Medications',
    description: 'High-alert medications are medications that bear a heightened risk of causing significant patient harm when used in error. Hospitals must identify high-alert medications and implement protocols to reduce risk.',
    category: 'JC',
    surveyorTips: 'Surveyors check that your high-alert medication list is published, that staff can name the high-alert medications used in their unit, and that required safeguards (double-checks, smart pump libraries, concentration limits) are in place. Insulin, heparin, and concentrated electrolytes must be included.',
    keywords: 'high-alert medications insulin heparin concentrated electrolytes double-check',
  },
  {
    id: 'jc-mm2',
    standard: 'MM.04.01.01',
    title: 'Medication Orders and Prescribing',
    description: 'Verbal and telephone orders for medications must be verified by the prescriber within a defined timeframe. Hospitals must define what information is required in a complete medication order.',
    category: 'JC',
    surveyorTips: 'Surveyors pull records looking for verbal/telephone order sign-off. Any verbal order not authenticated within the time defined in your policy (typically 24-48 hours) is a finding. Review CPOE usage to minimize verbal orders. Check that PRN order pain reassessment documentation is complete.',
    keywords: 'verbal orders telephone orders authentication CPOE prescribing',
  },
  // ── OSHA Standards ───────────────────────────────────────────────
  {
    id: 'osha-bloodborne',
    standard: '29 CFR 1910.1030',
    title: 'Bloodborne Pathogens',
    description: 'Employers must protect workers from exposure to blood and other potentially infectious materials. Requirements include: Exposure Control Plan, HBV vaccination program, PPE provision, training, and post-exposure protocols.',
    category: 'OSHA',
    surveyorTips: 'OSHA inspectors request the written Exposure Control Plan first - it must be updated annually. Verify that sharps injury logs are complete, all occupationally exposed employees have been offered hepatitis B vaccination, and annual bloodborne pathogen training records are current. Review your post-exposure evaluation process.',
    keywords: 'bloodborne pathogens exposure control plan hepatitis B sharps PPE training',
  },
  {
    id: 'osha-hazcom',
    standard: '29 CFR 1910.1200',
    title: 'Hazard Communication (HazCom) / GHS',
    description: 'Employees must be informed about hazardous chemicals they may be exposed to. Requirements include: chemical inventory, Safety Data Sheets (SDS) accessible to all employees, container labeling with GHS pictograms, and employee training.',
    category: 'OSHA',
    surveyorTips: 'OSHA inspectors spot-check that SDS are accessible in all areas where chemicals are used (not just the safety office). Verify your chemical inventory is complete, all containers are labeled with GHS elements, and affected employees received HazCom training within 30 days of hire and when new chemicals are introduced.',
    keywords: 'HazCom GHS SDS safety data sheets chemical inventory labeling training',
  },
  {
    id: 'osha-respiratory',
    standard: '29 CFR 1910.134',
    title: 'Respiratory Protection',
    description: 'When engineering controls and work practice controls are not sufficient to reduce employee exposure, respiratory protection must be provided. Written Respiratory Protection Program required. Medical evaluation, fit testing, and training must be documented.',
    category: 'OSHA',
    surveyorTips: 'N95 respirator programs are commonly inspected in healthcare. Verify annual fit test records exist for all employees required to wear N95s, that the written program is current, and that employees received training. Voluntary use of respirators requires employees to receive Appendix D of the standard.',
    keywords: 'respiratory protection N95 fit test written program medical evaluation training',
  },
  {
    id: 'osha-300log',
    standard: '29 CFR 1904',
    title: 'Recordkeeping: OSHA 300 / 300A / 301',
    description: 'Employers must record and report work-related fatalities, injuries, and illnesses. OSHA 300 Log must be maintained throughout the year. OSHA 300A Summary must be posted from February 1 to April 30. OSHA 301 must be completed within 7 days of each recordable incident.',
    category: 'OSHA',
    surveyorTips: 'OSHA inspectors often request the last three years of 300 Logs and compare to workers\' compensation records to verify completeness. Ensure your 300A was posted on time. Common errors: failing to record restricted work cases, not completing 301 forms within 7 days, and not recording DART cases correctly.',
    keywords: 'OSHA 300 300A 301 recordkeeping injury illness log posting',
  },
  {
    id: 'osha-violence',
    standard: '29 CFR 1904.35',
    title: 'Workplace Violence Prevention in Healthcare',
    description: 'Healthcare employers must provide a safe workplace free from recognized hazards. OSHA enforces workplace violence prevention through the General Duty Clause. Recording of assaults resulting in medical treatment or restricted work is required on the OSHA 300 Log.',
    category: 'OSHA',
    surveyorTips: 'Document all workplace violence incidents, including those not meeting recordable criteria. A comprehensive Workplace Violence Prevention Program with hazard analysis, engineering controls, and training is expected. Surveyors will ask about incident trends, reporting culture, and management follow-up on reported incidents.',
    keywords: 'workplace violence prevention healthcare assaults General Duty Clause recording',
  },
  {
    id: 'osha-ergonomics',
    standard: '29 CFR 1910 (General Duty)',
    title: 'Safe Patient Handling and Ergonomics',
    description: 'Healthcare employers must address musculoskeletal injuries from patient lifting and repositioning. A Safe Patient Handling program with mechanical lift equipment reduces injury risk. Many states have enacted Safe Patient Handling laws.',
    category: 'OSHA',
    surveyorTips: 'Check that mechanical lifting equipment is available on all units where transfers occur, that equipment is maintained and inspected regularly, and that staff are trained in its use. Review your OSHA 300 Log for MSD cases - a pattern of musculoskeletal injuries signals need for a program update.',
    keywords: 'safe patient handling ergonomics lifting MSD musculoskeletal mechanical lift',
  },
  {
    id: 'osha-exit',
    standard: '29 CFR 1910.36',
    title: 'Means of Egress',
    description: 'Exit routes must be permanent, adequate, and properly maintained. Exit signs must be illuminated. Exit access, exit, and exit discharge areas must be unobstructed.',
    category: 'OSHA',
    surveyorTips: 'Walk all clinical areas looking for exit signs with burned-out bulbs, blocked exits, locked doors without proper hardware, and storage in exit corridors. OSHA inspectors find blocked exits in nearly every healthcare inspection - storage creep in stairwells and exit corridors is a persistent issue.',
    keywords: 'exit routes egress exit signs obstructions storage corridors stairwells',
  },
  // ── Arizona ADHS Standards ────────────────────────────────────────
  {
    id: 'adhs-r9-10-101',
    standard: 'A.A.C. R9-10-101',
    title: 'General Hospital Licensure Definitions',
    description: 'Definitions applicable to hospital licensing requirements under the Arizona Administrative Code. All hospitals operating in Arizona must comply with Title 9, Chapter 10 of the Administrative Code.',
    category: 'ADHS',
    surveyorTips: 'ADHS surveyors use the R9-10 standards in conjunction with CMS CoPs. Ensure your compliance team has access to the current version of the AZ Administrative Code, as ADHS updates rules independently of CMS. Subscribe to ADHS listserv notifications for rule changes.',
    keywords: 'Arizona ADHS licensure hospital definitions Title 9 Chapter 10',
  },
  {
    id: 'adhs-r9-10-202',
    standard: 'A.A.C. R9-10-202',
    title: 'Patient Rights and Responsibilities (AZ)',
    description: 'Arizona requires hospitals to provide patients with written notice of their rights and responsibilities. The notice must be available in English and Spanish at minimum. Patients must be informed of the grievance process and the right to contact ADHS.',
    category: 'ADHS',
    surveyorTips: 'ADHS surveyors specifically check for Spanish-language patient rights materials. Verify that your patient rights notice includes the ADHS contact information for complaints. The grievance log must document that patients were informed of their right to file a complaint with ADHS.',
    keywords: 'Arizona patient rights Spanish ADHS contact grievance notice',
  },
  {
    id: 'adhs-r9-10-301',
    standard: 'A.A.C. R9-10-301',
    title: 'Nursing Services (AZ)',
    description: 'Arizona nursing service requirements supplement CMS CoPs. Licensed nursing staff assignments must reflect patient acuity. Arizona requires specific nurse-to-patient ratios in certain unit types. Charge nurses must meet defined qualifications.',
    category: 'ADHS',
    surveyorTips: 'ADHS surveyors may cite ratio violations if staffing assignments do not reflect patient acuity scoring. Ensure acuity assessment documentation in the medical record supports your staffing decisions. Review your charge nurse qualifications and competency documentation.',
    keywords: 'Arizona nursing ratios acuity charge nurse staffing assignments',
  },
  {
    id: 'adhs-r9-10-401',
    standard: 'A.A.C. R9-10-401',
    title: 'Infection Control (AZ)',
    description: 'Arizona requires hospitals to report certain communicable diseases and conditions to ADHS. Hospitals must participate in Arizona healthcare-associated infection reporting programs. Outbreak response protocols must be established and exercised.',
    category: 'ADHS',
    surveyorTips: 'Verify that your infection preventionist is enrolled in NHSN (National Healthcare Safety Network) and reporting HAI data as required by ADHS. Review your list of reportable conditions and ensure your process for reporting to ADHS is documented and staff are trained to initiate reports within required timeframes.',
    keywords: 'Arizona infection control communicable disease reporting NHSN HAI outbreak',
  },
  {
    id: 'adhs-r9-10-501',
    standard: 'A.A.C. R9-10-501',
    title: 'Medical Staff (AZ)',
    description: 'Arizona requires hospitals to verify practitioner licensure with the Arizona Medical Board or applicable licensing board prior to granting privileges. Background checks on credentialing applicants are required.',
    category: 'ADHS',
    surveyorTips: 'ADHS surveyors will pull credentialing files and verify primary source verification was completed, including AZ Board of Medical Examiners license verification. Ensure your credentialing software flags licenses expiring within 90 days so re-verification can occur proactively.',
    keywords: 'Arizona medical board license verification credentialing background check privileges',
  },
  {
    id: 'adhs-r9-10-601',
    standard: 'A.A.C. R9-10-601',
    title: 'Pharmaceutical Services (AZ)',
    description: 'Arizona Board of Pharmacy requirements apply to hospital pharmacies. Hospitals must maintain a current AZ pharmacy permit. Pharmacist-in-charge must hold a current AZ license. Drug storage, security, and dispensing must comply with state requirements.',
    category: 'ADHS',
    surveyorTips: 'Verify AZ Board of Pharmacy hospital permit is current and posted. All pharmacists and pharmacy techs must hold current AZ licenses. ADHS surveyors will check controlled substance records for accuracy and verify that required security features are in place for scheduled drug storage.',
    keywords: 'Arizona pharmacy permit Board of Pharmacy controlled substances pharmacist license',
  },
  {
    id: 'adhs-r9-10-701',
    standard: 'A.A.C. R9-10-701',
    title: 'Physical Environment and Safety (AZ)',
    description: 'Hospitals must comply with the Arizona State Fire Marshal requirements in addition to Life Safety Code. ADHS conducts environment of care surveys that include life safety inspections. Construction and renovation projects require ADHS plan review and approval.',
    category: 'ADHS',
    surveyorTips: 'Any construction or renovation project - including minor work in patient areas - may require ADHS plan review. Contact your ADHS regional office before starting projects. Maintain documentation of State Fire Marshal inspection reports and ensure all corrective actions are completed and closed.',
    keywords: 'Arizona Fire Marshal life safety construction renovation environment plan review',
  },
  {
    id: 'adhs-r9-10-801',
    standard: 'A.A.C. R9-10-801',
    title: 'Incident Reporting (AZ)',
    description: 'Arizona requires hospitals to report certain serious reportable events to ADHS within specified timeframes. Reportable events include: patient deaths in unexpected circumstances, serious injuries related to care, and elopements. Reports must be submitted to ADHS within defined timeframes.',
    category: 'ADHS',
    surveyorTips: 'Maintain a log of all events evaluated for reportability, even those determined not to be reportable, with documentation of the determination rationale. ADHS expects reports to be submitted within 5 calendar days for most events. Delayed or missing reports can trigger complaint investigations.',
    keywords: 'Arizona incident reporting serious events patient death elopement ADHS report 5-day',
  },
  {
    id: 'adhs-r9-10-901',
    standard: 'A.A.C. R9-10-901',
    title: 'Emergency Services (AZ)',
    description: 'Arizona requires hospitals with emergency services to meet defined capabilities standards. Emergency departments must have qualified personnel available 24/7. EMTALA requirements are enforced jointly by CMS and ADHS.',
    category: 'ADHS',
    surveyorTips: 'EMTALA compliance is jointly reviewed by CMS and ADHS. Verify all staff who conduct medical screening exams are listed in your medical staff bylaws as qualified to do so. Keep your EMTALA log current and ensure all transfers meet the certification and consent requirements.',
    keywords: 'EMTALA emergency services medical screening Arizona ADHS 24-hour',
  },
  {
    id: 'adhs-r9-10-1001',
    standard: 'A.A.C. R9-10-1001',
    title: 'Quality Management (AZ)',
    description: 'Arizona requires hospitals to have a quality management program that meets both CMS QAPI and ADHS standards. Serious reportable events must be reviewed with root cause analysis. Findings and corrective actions must be documented.',
    category: 'ADHS',
    surveyorTips: 'ADHS surveyors review your RCA documentation for serious events. The RCA must identify contributing factors, not just immediate causes, and corrective actions must address systemic issues. Show evidence that the quality committee reviewed RCA findings and approved the corrective action plan.',
    keywords: 'Arizona quality management RCA root cause analysis serious event quality committee',
  },
];
