'use client';

import { useState } from 'react';
import { FileText } from 'lucide-react';

export function Osha300AButton() {
  const [loading, setLoading] = useState(false);
  const year = new Date().getFullYear();

  async function handleExport() {
    setLoading(true);
    try {
      const res = await fetch(`/api/workforce-health/osha/export?year=${year}`);
      const d = await res.json();

      const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>OSHA 300A Summary ${d.year}</title>
<style>
  body{font-family:Arial,sans-serif;font-size:12px;color:#000;margin:24px}
  h1{font-size:16px;margin:0 0 4px}
  .sub{font-size:11px;color:#555;margin:0 0 16px}
  table{width:100%;border-collapse:collapse;margin-top:8px}
  th,td{border:1px solid #333;padding:6px 10px;text-align:left}
  th{background:#f0f0f0;font-weight:bold;font-size:11px}
  .num{text-align:right;font-weight:bold}
  .section{margin-top:20px}
  .section h2{font-size:13px;border-bottom:2px solid #333;padding-bottom:4px;margin-bottom:8px}
  .footer{margin-top:32px;font-size:10px;color:#777;border-top:1px solid #ccc;padding-top:8px}
  @media print{body{margin:12px}}
</style></head><body>
<h1>OSHA Form 300A &mdash; Summary of Work-Related Injuries and Illnesses</h1>
<p class="sub">Year: ${d.year} &nbsp;|&nbsp; Facility: ${d.facilityName} &nbsp;|&nbsp; ${d.facilityAddress}</p>

<div class="section">
<h2>Annual Summary Totals (Recordable Cases Only)</h2>
<table>
  <tr><th style="width:70%">Category</th><th>Count</th></tr>
  <tr><td>Total recordable cases (Column G)</td><td class="num">${d.totalCases}</td></tr>
  <tr><td>Cases with days away from work (Column H)</td><td class="num">${d.daysAwayCases}</td></tr>
  <tr><td>Cases with job transfer or restriction only (Column I)</td><td class="num">${d.jobTransferCases}</td></tr>
  <tr><td>Other recordable cases (Column J)</td><td class="num">${d.otherRecordableCases}</td></tr>
  <tr><td>Deaths (Column E)</td><td class="num">${d.deaths}</td></tr>
</table>
</div>

<div class="section">
<h2>Number of Days</h2>
<table>
  <tr><th style="width:70%">Category</th><th>Days</th></tr>
  <tr><td>Total days away from work (Column K)</td><td class="num">${d.totalDaysAway}</td></tr>
  <tr><td>Total days of job transfer or restriction (Column L)</td><td class="num">${d.totalDaysRestriction}</td></tr>
</table>
</div>

<div class="section">
<h2>Injury and Illness Types</h2>
<table>
  <tr><th style="width:70%">Type</th><th>Cases</th></tr>
  <tr><td>(M1) Injuries</td><td class="num">${d.totalCases - d.needlestickCases}</td></tr>
  <tr><td>(M2) Skin disorders</td><td class="num">0</td></tr>
  <tr><td>(M3) Respiratory conditions</td><td class="num">0</td></tr>
  <tr><td>(M4) Poisonings</td><td class="num">0</td></tr>
  <tr><td>(M5) Hearing loss</td><td class="num">0</td></tr>
  <tr><td>(M6) All other illnesses (needlestick/sharps)</td><td class="num">${d.needlestickCases}</td></tr>
</table>
</div>

<div class="section">
<h2>Notable Categories (not OSHA 300A fields &mdash; for internal use)</h2>
<table>
  <tr><th style="width:70%">Category</th><th>Cases</th></tr>
  <tr><td>Patient handling / musculoskeletal</td><td class="num">${d.musculoskeletalCases}</td></tr>
  <tr><td>Workplace violence</td><td class="num">${d.workplaceViolenceCases}</td></tr>
</table>
</div>

<div class="footer">
  <p>Generated by NyxCitadel&trade; &mdash; ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
  <p>Post this summary in a visible location from February 1 through April 30, ${d.year + 1} per 29 CFR 1904.32.</p>
</div>
</body></html>`;

      const w = window.open('', '_blank');
      if (w) {
        w.document.write(html);
        w.document.close();
        w.focus();
        setTimeout(() => w.print(), 500);
      }
    } finally {
      setLoading(false);
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={loading}
      className="flex items-center gap-2 px-4 py-2 rounded-lg border border-amber-400/40 text-amber-300 hover:bg-amber-400/10 text-sm font-medium transition-colors disabled:opacity-50"
    >
      <FileText className="w-4 h-4" />
      {loading ? 'Generating...' : `Export 300A Summary (${year})`}
    </button>
  );
}
