import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import Anthropic from '@anthropic-ai/sdk';
import { prisma } from '@/lib/prisma';
import { generateCapNumber } from '@/lib/utils';
import { logAudit } from '@/lib/audit';

export const dynamic = 'force-dynamic';

const SYSTEM_PROMPT = `You are Sentry, a cute robot compliance assistant (🤖) for acute psychiatric hospitals.
You specialize in:
- Joint Commission (JC) standards, especially behavioral health, NPSG, and emergency management
- CMS Conditions of Participation (CoPs) including 482.13 patient rights and grievance requirements
- Arizona ADHS regulations for behavioral health facilities (A.A.C. R9-10)
- QAPI methodology, PDSA cycles, and performance improvement
- Root cause analysis (RCA), corrective action plans (CAP), and plan of correction (POC)
- HBIPS core measures and psychiatric quality metrics
- Restraint and seclusion regulations (CMS 482.13(e))
- Infection control, HVA/emergency preparedness, and governance

Always provide accurate, practical guidance. When citing specific standards, include the standard number (e.g., JC EC.02.06.01, CMS 482.13). Acknowledge uncertainty when appropriate and recommend verifying against official regulatory publications.`;

interface Message {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

type DraftActionType = 'CREATE_CAP_DRAFT' | 'CREATE_INCIDENT_DRAFT' | 'CREATE_CALENDAR_DRAFT';

type DraftActionRequest = {
  type: DraftActionType;
  payload?: Record<string, unknown>;
};

type ActionSuggestion = {
  type: DraftActionType;
  payload: Record<string, unknown>;
};

function stripActionTag(text: string) {
  return text.replace(/<sentry_action>[\s\S]*?<\/sentry_action>/i, '').trim();
}

function parseActionSuggestion(text: string): ActionSuggestion | null {
  const match = text.match(/<sentry_action>([\s\S]*?)<\/sentry_action>/i);
  if (!match) return null;
  try {
    const parsed = JSON.parse(match[1]) as ActionSuggestion;
    if (!parsed?.type || !parsed?.payload) return null;
    if (!['CREATE_CAP_DRAFT', 'CREATE_INCIDENT_DRAFT', 'CREATE_CALENDAR_DRAFT'].includes(parsed.type)) return null;
    return parsed;
  } catch {
    return null;
  }
}

function asString(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback;
}

async function executeDraftAction(
  req: NextRequest,
  userId: string,
  facilityId: string,
  actionRequest: DraftActionRequest
) {
  const payload = actionRequest.payload ?? {};

  if (actionRequest.type === 'CREATE_CAP_DRAFT') {
    const title = asString(payload.title, 'Untitled CAP draft').slice(0, 180);
    const description = asString(payload.description, 'Draft CAP generated by Sentry.');
    const priority = asString(payload.priority, 'HIGH');
    const source = asString(payload.source, 'OTHER');
    const targetDate = asString(payload.targetDate, new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString());

    const cap = await prisma.correctiveActionPlan.create({
      data: {
        facilityId,
        capNumber: generateCapNumber(),
        title: `[DRAFT] ${title}`,
        description,
        source: source as never,
        priority: priority as never,
        correctionPlan: description,
        targetDate: new Date(targetDate),
        status: 'OPEN',
      },
    });

    await logAudit({
      userId,
      action: 'CREATE_CAP_DRAFT_BY_SENTRY',
      entityType: 'CorrectiveActionPlan',
      entityId: cap.id,
      changes: payload,
      req,
    });

    return {
      ok: true,
      created: {
        type: 'CAP',
        id: cap.id,
        label: cap.capNumber,
        href: `/trackers/caps/${cap.id}`,
      },
    };
  }

  if (actionRequest.type === 'CREATE_INCIDENT_DRAFT') {
    const incidentType = asString(payload.incidentType, 'OTHER');
    const severity = asString(payload.severity, 'MODERATE');
    const incidentDate = asString(payload.incidentDate, new Date().toISOString());
    const briefDescription = asString(payload.briefDescription, 'Draft incident report generated by Sentry.');
    const location = asString(payload.location, 'TBD');
    const unitName = asString(payload.unitName, 'TBD');

    const year = new Date().getFullYear();
    const count = await prisma.incidentReport.count({ where: { facilityId } });
    const irNumber = `IR-${year}-${String(count + 1).padStart(4, '0')}`;

    const item = await prisma.incidentReport.create({
      data: {
        facilityId,
        irNumber,
        incidentDate: new Date(incidentDate),
        incidentType: incidentType as never,
        severity: severity as never,
        briefDescription: `[DRAFT] ${briefDescription}`,
        location,
        unitName,
        status: 'OPEN',
      },
    });

    await logAudit({
      userId,
      action: 'CREATE_INCIDENT_DRAFT_BY_SENTRY',
      entityType: 'IncidentReport',
      entityId: item.id,
      changes: payload,
      req,
    });

    return {
      ok: true,
      created: {
        type: 'IncidentReport',
        id: item.id,
        label: item.irNumber,
        href: `/trackers/ir-iad/${item.id}`,
      },
    };
  }

  if (actionRequest.type === 'CREATE_CALENDAR_DRAFT') {
    const title = asString(payload.title, 'Untitled calendar draft');
    const dueDate = asString(payload.dueDate, new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString());
    const category = asString(payload.category, 'OTHER');
    const description = asString(payload.description, 'Draft calendar event generated by Sentry.');
    const priority = asString(payload.priority, 'MEDIUM');

    const event = await prisma.calendarEvent.create({
      data: {
        facilityId,
        title: `[DRAFT] ${title}`,
        description,
        dueDate: new Date(dueDate),
        category: category as never,
        priority: priority as never,
        status: 'UPCOMING',
      },
    });

    await logAudit({
      userId,
      action: 'CREATE_CALENDAR_DRAFT_BY_SENTRY',
      entityType: 'CalendarEvent',
      entityId: event.id,
      changes: payload,
      req,
    });

    return {
      ok: true,
      created: {
        type: 'CalendarEvent',
        id: event.id,
        label: event.title,
        href: `/calendar/${event.id}`,
      },
    };
  }

  return { ok: false, error: 'Unsupported action request.' };
}

async function getFacilityContext(facilityId: string) {
  const now = new Date();
  const in30Days = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

  const [
    overdueCalendar,
    dueSoonCalendar,
    openCaps,
    overdueCaps,
    recentIncidents,
    expiringTraining,
  ] = await Promise.all([
    prisma.calendarEvent.count({
      where: { facilityId, dueDate: { lt: now }, completedDate: null, status: { notIn: ['COMPLETED', 'WAIVED', 'NA'] } },
    }),
    prisma.calendarEvent.count({
      where: { facilityId, dueDate: { gte: now, lte: in30Days }, status: { notIn: ['COMPLETED', 'WAIVED', 'NA'] } },
    }),
    prisma.correctiveActionPlan.count({
      where: { facilityId, status: { notIn: ['COMPLETED', 'VERIFIED'] } },
    }),
    prisma.correctiveActionPlan.count({
      where: { facilityId, targetDate: { lt: now }, status: { notIn: ['COMPLETED', 'VERIFIED'] } },
    }),
    prisma.incidentReport.findMany({
      where: { facilityId },
      orderBy: { incidentDate: 'desc' },
      take: 3,
      select: { irNumber: true, incidentType: true, severity: true, status: true },
    }),
    prisma.trainingRecord.count({
      where: { facilityId, expiryDate: { gte: now, lte: in30Days }, status: { not: 'EXEMPT' } },
    }),
  ]);

  return {
    overdueCalendar,
    dueSoonCalendar,
    openCaps,
    overdueCaps,
    expiringTraining,
    recentIncidents,
  };
}

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json({
      reply: "Sentry is not configured yet. Please ask your administrator to add an Anthropic API key to enable Sentry.",
    });
  }

  let body: { message?: string; history?: Message[]; actionRequest?: DraftActionRequest };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  if (body.actionRequest) {
    try {
      const result = await executeDraftAction(req, session.user.id, session.user.facilityId, body.actionRequest);
      return NextResponse.json(result);
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Failed to execute action.';
      return NextResponse.json({ ok: false, error: msg }, { status: 400 });
    }
  }

  const { message, history = [] } = body;
  if (!message?.trim()) {
    return NextResponse.json({ error: 'Message is required' }, { status: 400 });
  }

  const facilityContext = await getFacilityContext(session.user.facilityId);
  const contextString = JSON.stringify(facilityContext, null, 2);

  const sentrySystemPrompt = `${SYSTEM_PROMPT}

Current facility context snapshot:
${contextString}

If the user asks to create a draft CAP, incident report, or calendar event, include ONE XML-like action tag at the end of your answer:
<sentry_action>{"type":"CREATE_CAP_DRAFT|CREATE_INCIDENT_DRAFT|CREATE_CALENDAR_DRAFT","payload":{...}}</sentry_action>

Only include that tag when explicitly useful. Keep payload minimal and valid.`;

  // Build message array from prior history (capped at last 20) + new user message.
  // Filter out any system messages — Anthropic takes system as a top-level param.
  const anthropicMessages = [
    ...history.slice(-20).filter((m) => m.role !== 'system').map((m) => ({
      role: m.role as 'user' | 'assistant',
      content: m.content,
    })),
    { role: 'user' as const, content: message.trim() },
  ];

  const client = new Anthropic({ apiKey });

  try {
    const response = await client.messages.create({
      model: 'claude-3-5-haiku-20241022',
      max_tokens: 1024,
      system: sentrySystemPrompt,
      messages: anthropicMessages,
    });

    const block = response.content[0];
    const rawReply = block.type === 'text' ? block.text : 'No response received.';
    const actionSuggestion = parseActionSuggestion(rawReply);
    const reply = stripActionTag(rawReply);
    return NextResponse.json({ reply, actionSuggestion });
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Claude request failed';
    return NextResponse.json({ error: msg }, { status: 502 });
  }
}
